export default {
  BAD_REQUEST: "BAD_REQUEST",

  CONFLICT: "CONFLICT",

  FORBIDDEN: "FORBIDDEN",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_DATA: "INVALID_DATA",

  NOT_FOUND: "NOT_FOUND",

  PRODUCTS_NOT_FOUND: "PRODUCTS_NOT_FOUND",

  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
} as const;
