const ONE_SECOND = 1000;
const FIVE_SECONDS = ONE_SECOND * 5;
const TEN_SECONDS = ONE_SECOND * 10;
const ONE_MINUTE = ONE_SECOND * 60;
const TWO_MINUTES = ONE_MINUTE * 2;
const THREE_MINUTES = ONE_MINUTE * 3;
const FOUR_MINUTES = ONE_MINUTE * 4;
const FIVE_MINUTES = ONE_MINUTE * 5;
const FIFTEEN_MINUTES = ONE_MINUTE * 15;
const THIRTY_MINUTES = ONE_MINUTE * 30;
const ONE_HOUR = ONE_MINUTE * 60;
const ONE_DAY = ONE_HOUR * 24;

export const timeConstant = {
  ONE_SECOND,
  FIVE_SECONDS,
  TEN_SECONDS,
  ONE_MINUTE,
  TWO_MINUTES,
  THREE_MINUTES,
  FOUR_MINUTES,
  FIVE_MINUTES,
  FIFTEEN_MINUTES,
  THIRTY_MINUTES,
  ONE_HOUR,
  ONE_DAY,
};
