export default {
  FIELD_REQUIRED: "FIELD_REQUIRED",

  INVALID_BOOLEAN_FORMAT: "INVALID_BOOLEAN_FORMAT",
  INVALID_FORMAT: "INVALID_FORMAT",
  INVALID_NUMBER: "INVALID_NUMBER",
  INVALID_STRING: "INVALID_STRING",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_PHONE: "INVALID_PHONE",
  INVALID_UUID_FORMAT: "INVALID_UUID_FORMAT",
} as const;
